name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Déclenche le workflow à chaque push sur la branche "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Étape 2 : Installer pnpm
      - name: Setup pnpm
        run: |
          npm install -g pnpm

      # Étape 3 : Installer les dépendances avec pnpm
      - name: Install dependencies
        run: pnpm install

      # Étape 4 : Générer les fichiers statiques avec pnpm
      - name: Generate static files
        env:
          BASE_URL: /nom-depot/ # Remplace par le nom de ton dépôt GitHub
        run: pnpm run generate

      # Étape 5 : Déployer sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
